import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Data Processing Agreement (DPA) — Sitebot',
  description: 'How Sitebot acts as data processor for the data of visitors who use the widget installed on a Customer\'s site.',
};

const SECTIONS = [
  { id: 'roles', title: '1. Roles: who is controller and who is processor' },
  { id: 'objeto', title: '2. Object and duration of processing' },
  { id: 'instrucciones', title: '3. Processing only under instructions' },
  { id: 'datos-tratados', title: '4. Data processed and data subjects' },
  { id: 'subencargados', title: '5. Subprocessors' },
  { id: 'seguridad', title: '6. Security measures' },
  { id: 'confidencialidad', title: '7. Confidentiality' },
  { id: 'derechos', title: '8. Assistance with data subject rights' },
  { id: 'incidentes', title: '9. Incident notification' },
  { id: 'devolucion', title: '10. Return or deletion of data' },
  { id: 'auditorias', title: '11. Audits' },
  { id: 'responsabilidades', title: '12. Customer responsibilities' },
  { id: 'vigencia', title: '13. Term' },
  { id: 'contacto', title: '14. Contact' },
];

export default function ProcesamientoDatosPage() {
  return (
    <LegalPage
      title="Data Processing Agreement"
      updatedAt="September 18, 2026"
      sections={SECTIONS}
    >
      <p>
        This Data Processing Agreement (&quot;DPA&quot;) forms part of the{' '}
        <a href="/legal/terminos">Terms of Service</a> and applies to any
        Customer who installs the Sitebot chat widget on their own
        website, allowing end visitors to interact with it. It describes
        how we process, on the Customer's behalf, the personal data of
        those visitors.
      </p>

      <h2 id="roles">1. Roles: who is controller and who is processor</h2>
      <p>
        With respect to the personal data of the <strong>end
        visitors</strong> who use the widget on the Customer's site:
      </p>
      <ul>
        <li>The <strong>Customer</strong> is the data controller: they decide which site is crawled, what content is indexed, how the bot is configured, and what the resulting conversations are used for.</li>
        <li><strong>Sitebot</strong> acts as the data processor: it processes that data solely to provide the Service contracted by the Customer, following their configuration.</li>
      </ul>
      <p>
        With respect to the Customer's own account data (email, password,
        configuration), Sitebot is the data controller, as explained in
        the{' '}
        <a href="/legal/privacidad">Privacy Policy</a>.
      </p>

      <h2 id="objeto">2. Object and duration of processing</h2>
      <p>
        The object of the processing is to allow the widget to answer
        questions from the Customer's site visitors using that site's
        content, and to show the Customer the resulting history and
        analytics. The processing lasts for as long as the Customer keeps
        the site active in their account.
      </p>

      <h2 id="instrucciones">3. Processing only under instructions</h2>
      <p>
        Sitebot processes visitor data solely in accordance with the
        Customer's documented instructions, expressed through the
        configuration available in the dashboard (site to crawl, bot
        settings, allowed origins, usage limits). Sitebot does not use
        that data for any purpose of its own, such as training third-party
        models, advertising, or transferring it to another Customer.
      </p>
      <p>
        If we consider that a Customer instruction infringes applicable
        data protection regulations, we will inform them before carrying
        it out.
      </p>

      <h2 id="datos-tratados">4. Data processed and data subjects</h2>
      <p><strong>Data subjects:</strong> visitors to the Customer's website who interact with the chat widget.</p>
      <p><strong>Categories of data:</strong></p>
      <ul>
        <li>Content of the messages written by the visitor in the chat.</li>
        <li>Responses generated by the bot and the sources cited.</li>
        <li>Rating of the response (👍/👎), if the visitor uses it.</li>
        <li>Technical conversation session identifier.</li>
        <li>Any personal data the visitor voluntarily chooses to write in their message (for example, their name or email if they mention them while asking something).</li>
      </ul>
      <p>
        Sitebot does not actively request identifying data from end
        visitors; such data only arises if the visitor voluntarily
        includes it in their message.
      </p>

      <h2 id="subencargados">5. Subprocessors</h2>
      <p>
        The Customer authorizes Sitebot to use the following subprocessors
        to provide the Service:
      </p>
      <table>
        <thead>
          <tr>
            <th>Subprocessor</th>
            <th>Function</th>
            <th>Processing location</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>OpenAI (or another compatible language model provider, configurable by Sitebot)</td>
            <td>Generation of the chat response from the relevant content found on the site</td>
            <td>Outside Argentina (including the U.S.), under its own data protection commitments</td>
          </tr>
          <tr>
            <td>Hosting and infrastructure provider</td>
            <td>Hosting of the application and the database</td>
            <td>Depending on the infrastructure provider contracted at any given time</td>
          </tr>
        </tbody>
      </table>
      <p>
        Sitebot will inform the Customer of any change to this list of
        subprocessors with reasonable advance notice, so the Customer can
        object for justified reasons related to data protection.
      </p>

      <h2 id="seguridad">6. Security measures</h2>
      <p>
        Sitebot applies the technical and organizational measures
        described in the security section of the{' '}
        <a href="/legal/privacidad">Privacy Policy</a> (mandatory
        authentication, hashed passwords, secure session cookies, widget
        origin validation, protection against access to internal
        networks) to protect the data processed on the Customer's behalf.
      </p>

      <h2 id="confidencialidad">7. Confidentiality</h2>
      <p>
        Sitebot personnel or collaborators with access to visitor data are
        subject to confidentiality obligations, and access is limited to
        what is necessary to operate and support the Service.
      </p>

      <h2 id="derechos">8. Assistance with data subject rights</h2>
      <p>
        If a visitor exercises before the Customer a right of access,
        rectification, erasure, or objection over data held by Sitebot,
        the Customer can resolve it directly from the dashboard (for
        example, reviewing or deleting conversations), or request our
        assistance by writing to{' '}
        <a href="mailto:hola@sitebot.dev">hola@sitebot.dev</a>.
      </p>

      <h2 id="incidentes">9. Incident notification</h2>
      <p>
        If we detect a security breach affecting personal data processed
        on the Customer's behalf, we will notify them without undue
        delay, with the information available about its nature, scope,
        and the measures taken or proposed, so the Customer can comply
        with their own notification obligations if applicable.
      </p>

      <h2 id="devolucion">10. Return or deletion of data</h2>
      <p>
        Deleting a site from the dashboard immediately and irreversibly
        erases all of its indexed content, conversation history, and
        associated configuration from Sitebot's production systems,
        except for what must be retained in backups for a limited period
        as described in the{' '}
        <a href="/legal/privacidad">Privacy Policy</a>.
      </p>

      <h2 id="auditorias">11. Audits</h2>
      <p>
        The Customer may reasonably request information about the
        security measures and subprocessors used, to verify compliance
        with this Agreement. Given the size of the Service, this is
        handled through written documentation rather than on-site audits,
        unless otherwise agreed between the parties.
      </p>

      <h2 id="responsabilidades">12. Customer responsibilities</h2>
      <p>As the data controller, the Customer is responsible for:</p>
      <ul>
        <li>Having a legal basis (for example, their own privacy notice on their site) for their visitors to interact with the widget.</li>
        <li>Only submitting for crawling sites that they own or are authorized to crawl.</li>
        <li>Configuring the bot so that it does not prompt visitors to share unnecessary sensitive data.</li>
        <li>Handling requests from their own visitors in their capacity as controller toward them.</li>
      </ul>

      <h2 id="vigencia">13. Term</h2>
      <p>
        This Agreement remains in effect while the Customer uses the
        Service and keeps the widget installed on their site, and
        terminates together with the Terms of Service.
      </p>

      <h2 id="contacto">14. Contact</h2>
      <p>
        Questions about this Data Processing Agreement:{' '}
        <a href="mailto:hola@sitebot.dev">hola@sitebot.dev</a>.
      </p>

      <div className="legal-note">
        This document is an informational template inspired by the usual
        structure of a DPA and does not replace the advice of a lawyer.
        If you have Customers operating under the GDPR (European Union),
        you will likely need a version with standard contractual clauses
        (SCCs) for international data transfers and a more detailed
        technical annex; consult a professional before publishing it.
      </div>
    </LegalPage>
  );
}
